### ISSUE TITLE
Channel manipulation in grids

### ISSUE THREAD

**Issue by alecandido** [NNPDF/pineappl#149]
We should expose in the Python interface a function to manipulate luminosity function (in the first place, we need such a function in the Rust library).

Of course complicate manipulation are useless, but I would add a couple of simple ones:
- [ ] drop a lumi channel
- [ ] duplicate a lumi channel

Both of them should not involve generating further subgrids (but possibly dropping them), since the luminosity function can already optimize for equal channels. So, they are mostly about manipulating the luminosity function itself, rather than subgrids.

Even before, I will:
- [x] expose the `Grid.lumi` in the Python interface.

**Comment by AleCandido** [comment]
>  * [x]  expose the `Grid.lumi` in the Python interface.

Ok, this was simple. Done in 5f4902f6e665c7f1734353376abb46db9216ad16.

**Comment by AleCandido** [comment]
> This will probably not do what you'd like: it only returns the first flavour combination, but discards the remaining flavour combinations and factors.

I didn't understand...

The function I put above is just to query which is the luminosity function of the given grid. It is just a read function, not one for manipulating...

**Comment by cschwan** [comment]
This line:

https://github.com/N3PDF/pineappl/commit/5f4902f6e665c7f1734353376abb46db9216ad16#diff-1f7e3cc6363a7e6cbf795dc23874cf1e6c5d09b5b254ce0c8710e389f2f6badaR593

will return `uu~` if your lumi entry is `2 * uu~ + 1 * cc~`.

**Comment by AleCandido** [comment]
Ops, you're right...

Just copied from here:
https://github.com/N3PDF/pineappl/blob/5f4902f6e665c7f1734353376abb46db9216ad16/pineappl/src/fk_table.rs#L202
and I didn't notice the zero.

But you're right of course, let me iterate even on that dimension.

**Comment by AleCandido** [comment]
I just tested on a DIS grid, and even there it was working, but because in `yadism` we're always writing trivial lumis...

**Comment by cschwan** [comment]
Madgraph5 doesn't and usually they're very non-trivial because we assume a diagonal CKM matrix.

**Comment by AleCandido** [comment]
@cschwan check if now is more sensible

**Comment by cschwan** [comment]
That looks much better, but you're still throwing away the factors; without them the lumis are incomplete!

**Comment by AleCandido** [comment]
I had another try :)

**Comment by cschwan** [comment]
See also #165, this would simplify any querying/manipulation of the lumi function.

**Comment by AleCandido** [comment]
> * [ ] duplicate a lumi channel

I don't remember any longer why this would have been useful...

I still would like to be able to drop lumi channels (and consequently associated subgrids), and manipulate existing ones (i.e. manipulate/replace the content of a `LumiEntry`).
But for sure, what I don't want to do is to create additional channels, since there would be no subgrid associated, or I should copy all the existing subgrids associated to another channel.

**Comment by cschwan** [comment]
During the implementation of #199 I noticed that it's useful to have the following type of operation:

- `Grid::transform_lumi`: this operation converts a grid with `n` lumis into a grid with `m` new lumis, each having to be explicitly given to the function. The subgrids in the new grid are simply copies of the old subgrids specified by an index, and an additional factor allows to optionally rescale the new subgrids. That means this function accepts a `Vec` or a slice of tuples of the form `(LumiEntry, usize, f64)`.

This allows to implement the following operations:

- `to_flavor_basis`: imagine we have Drell-Yan grid which has the lumi function
  ```
  1 x (2, -1) + 1 x (4, -3)
  ```
  If we'd like to calculate the size of the up-anti-down channel and charm-anti-strange channel separately instead of together, we'd have to run
  ```
  grid.transform_lumi(vec![(lumi_entry![2, -1, 1.0], 0, 1.0), (lumi_entry![4, -3, 1.0], 0, 1.0)])
  ```
  This will change the grid to have two lumi entries,
  ```
  1 x (2, -1)
  1 x (4, -3)
  ```
  whose corresponding subgrids are copies of the old subgrid with index `0` and that are scaled with the factor `1.0` (nothing happens). Now the two channel are separate and we can use `pineappl channels` to figure out their size.
- we can use a variation of `to_flavor_basis` with `Grid::optimize_lumi` to produce a luminosity function that resembles what's needed in #199. We split up each `LumiEntry` into smaller pieces that either have complete overlap with all other split up lumis or no overlap. That, after optimizing the lumi function, will yield a new lumi function function with no overlaps sharing the largest number of channels together to keep the number of non-zero subgrids small.

**Comment by cschwan** [comment]
Another operation that we'll need is to change the factors of the luminosity function if we'd like to change the values of the CKM matrix, for instance.

**Comment by cschwan** [comment]
> Another operation that we'll need is to change the factors of the luminosity function if we'd like to change the values of the CKM matrix, for instance.

This can be done with with the `Grid::set_lumis` method and the CLI's [`write --rewrite-channels`](https://github.com/NNPDF/pineappl/commit/e006c95e508219f648821601399b8e410d039c64). [This gist](https://gist.github.com/cschwan/300604b6cad3e39d2eaf6e062c536219) shows an application of it.

**Comment by cschwan** [comment]
In meantime we have quite a few operations on channels:

- `Grid::split_channels`
- `Grid::delete_channels`
- `Grid::dedup_channels`

and also the general-purpose access methods:

- `Grid::channels`
- `Grid::channels_mut`

which allow to change the channels arbitrarily. I'm closing this Issue, if more methods are required, please open a new Issue.
