### ISSUE TITLE
Add support for different initial-state hadrons in the CLI

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pineappl#174]

**Comment by AleCandido** [comment]
I don't know exactly what's your purpose, but in case you want to do it for comparisons (show two columns aside for the two PDFs), maybe you might consider to have **multiple** PDFs, instead of two (just a list of space separated IDs).

For sure, there are cases in which it might not be possible, but sometimes might be relatively simple to do it.

Just a suggestion :)

**Comment by cschwan** [comment]
The idea is to support processes with different hadronic initial states, for instance proton-lead collisions, for which support in the CLI (and only there) is missing. Of course, eventually we'd like to generalize it to multiple 'PDFs', see here: https://github.com/N3PDF/pineappl/issues/172.

**Comment by AleCandido** [comment]
Sorry, my bad. I just misunderstood the purpose of the issue.

**Comment by cschwan** [comment]
No worries, it made me realize that the title is confusing!
