### ISSUE TITLE
Allow renormalization scale dependent rescaling of (sub)grids

### ISSUE THREAD

**Issue by cschwan** [NNPDF/pineappl#218]

**Comment by AleCandido** [comment]
I would say that is possible only using #222, since `indexed_iter()` is not mutable.

Of course, if you have a mutable subgrid you can iterate over it and replace its content by direct access. But, in principle, this is also possible without `indexed_iter()`, using a subgrid-type specific iteration (access and mutation is still subgrid-type specific).
